name: DGMS News Scraper

on:
  schedule:
    # Ye har 6 ghante mein chalega (UTC time)
    - cron: '0 */6 * * *'
    # - cron: '0 * * * *' # Har 1 ghante mein chalega
  workflow_dispatch: # Isse aap manually bhi "Run" button daba kar chala sakte ho

permissions:
  contents: write  # Ye zaroori line hai

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: pip install requests beautifulsoup4

    - name: Run Scraper
      run: python scraper.py  # Aapki python file ka naam yahan hona chahiye

    - name: Commit and Push
      env:
        GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add news.json
        git commit -m "Auto-update DGMS news" || exit 0
        # Niche wali line token ka use karegi
        git push https://x-access-token:${{ secrets.MY_GITHUB_TOKEN }}@github.com/${{ github.repository }}.git main